name: Build and Deploy Flutter Web

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}   # ex) your-dockerhub-username/futurefinder-flutter-web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: futurefinder_flutter

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Flutter 설치
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'

      # 3. 의존성 설치
      - name: Flutter pub get
        run: flutter pub get

      # 4. Flutter 웹 빌드
      - name: Flutter web build
        run: flutter build web

      # 5. Docker 로그인
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Docker 이미지 빌드 & Push
      - name: Build & Push Docker Image
        run: |
          docker build -t ${{ secrets.IMAGE_NAME }}:latest .
          docker push ${{ secrets.IMAGE_NAME }}:latest

      # 7. EC2 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /opt/futurefinder
            sudo docker compose pull
            sudo docker compose build --no-cache
            sudo docker compose up -d
